### ISSUE TITLE
[BUG] 最新版本配置好后只能上传纯色图片，否则会出错

### ISSUE THREAD

**Issue by vicar5235** [MYXXTS/Chevereto-Upload#4]
### 前置检查

- [X] [README](https://github.com/MYXXTS/Chevereto-Upload#readme)
- [X] 插件设置正确无误，且插件为最新版本
- [X] Chevereto 网站相关设置无误
- [X] [Issues](https://github.com/MYXXTS/Chevereto-Upload/issues?q=is%3Aissue+is%3Aclosed)

### 图床版本号

V4

### PicGo的版本

最新正式版 2.3.1

### 问题重现

配置好后只能上传纯色图片，否则会出错
图床后台手动上传是正常的，通过 ShareX 上传也是正常的，通过 pigco 上传纯色的照片是正常
但是正常截图其他稍微大一点的带内容的就没法上传了

### 相关日志

2023-11-02 20:36:08 [PicGo ERROR] {
  "method": "POST",
  "url": "http://xxxx/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "Empty upload source.",
        "code": 130
      },
      "status_txt": "Bad Request"
    }
  }
} 

### 相关截图

![](http://ct.vicar.cc:6060/images/2023/11/02/4d1216b2b2f5773c98e0097a31fc4b62.jpg)

**Comment by MYXXTS** [comment]
能否提供上传有问题的图片以供测试使用

**Comment by vicar5235** [comment]
好的，我用附件的方式上传到了这里，我的图床程序版本：4.0.7，部署在自己服务器上，管理员账户

<img width="600" alt="无法上传" src="https://github.com/MYXXTS/Chevereto-Upload/assets/35890470/fefd86c2-cb75-415a-8b0e-8d7143b165ab">
<img width="544" alt="成功上传" src="https://github.com/MYXXTS/Chevereto-Upload/assets/35890470/e2c87fdb-303a-4cd5-a8e5-0810ff86dc61">

**Comment by MYXXTS** [comment]
您好，多次尝试无法复现该问题，如可以的情况下，请您录制一个视频，视频内容包含您的 picgo 的配置项，和您的上传操作，如担心隐私问题，您可以联系QQ：151616171

**Comment by MYXXTS** [comment]
您是否填写了 Url Param 和 Source Param 中的任意配置项

**Comment by vicar5235** [comment]
你好，已经添加您的联系方式
