### ISSUE TITLE
[BUG] picgo upload 400错误

### ISSUE THREAD

**Issue by unclebryan719** [MYXXTS/Chevereto-Upload#7]
### 前置检查

- [X] [README](https://github.com/MYXXTS/Chevereto-Upload#readme)
- [X] [Issues](https://github.com/MYXXTS/Chevereto-Upload/issues?q=is%3Aissue+is%3Aclosed)
- [X] 插件设置正确无误，且插件为最新版本
- [X] Chevereto 网站相关设置无误，且网站程序版本为最新版本
- [X] 未对 Chevereto 网站接口代码进行修改

### chevereto 图床的版本（请前往控制台查看）

Chevereto Free 1.1.4

### PicGo的版本

picgo core 1.5.7

### 问题重现

操作流程：
执行命令：picgo upload /Users/unclebryan/Desktop/314341725531833_.pic.jpg
执行报400错误，错误在下面
配置说明：
cheveretov版本：Chevereto Free 1.1.4
node版本：使用nvm切换到nodev14.21.3
picgo core版本：1.5.7
picgo配置如下
{
  "picgoPlugins": {
    "picgo-plugin-cheveretov4": true,
    "picgo-plugin-web-uploader": true
  },
  "picBed": {
    "uploader": "cheveretov4",
    "current": "cheveretov4",
    "transformer": "path",
    "cheveretov4": {
      "cheveretoversion": "V3",
      "url": "http://xxx/api/1/upload",
      "key": "xxxx",
      "source_param": "source",
      "url_param": "url",
      "album_id": "1",
      "category_id": "",
      "description": ""
    }
  }
}

### 相关日志

➜  ~ picgo upload /Users/unclebryan/Desktop/314341725531833_.pic.jpg
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [cheveretov4]
[PicGo WARN]: failed
[PicGo ERROR]: Error: Request failed with status code 400
    at Object.handle (/Users/unclebryan/.picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async je.doUpload (/Users/unclebryan/.nvm/versions/node/v14.21.3/lib/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Users/unclebryan/.nvm/versions/node/v14.21.3/lib/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Users/unclebryan/.nvm/versions/node/v14.21.3/lib/node_modules/picgo/dist/index.cjs.js:1:74893)
    at async /Users/unclebryan/.nvm/versions/node/v14.21.3/lib/node_modules/picgo/dist/index.cjs.js:1:5821

### 相关截图

<img width="876" alt="Screen Shot 2024-09-10 at 00 17 34" src="https://github.com/user-attachments/assets/1b0ad558-aedd-4672-928c-4fe6375a88ae">

**Comment by MYXXTS** [comment]
已经定位到相关问题，晚点修复完成后会重新发布版本，请重新进行测试

**Comment by MYXXTS** [comment]
新版本已经发布，请尝试使用，并麻烦反馈，如果依旧存在问题，请重开此issue并补充说明

**Comment by unclebryan719** [comment]
牛逼 ~ 可以了
